### ISSUE TITLE
HTTP_UPDATE_FAILD Error (6): Update error: Stream Read Timeout

### ISSUE THREAD

**Issue by Franciscopcosta** [suculent/esp32-http-update#5]
Hi, i am getting this error:

HTTP_UPDATE_FAILD Error (6): Update error: Stream Read Timeout[V][HTTPClient.cpp:140] beginInternal(): url: http://xxx.xx.xxx.xxx:5555/firmware.bin
[D][HTTPClient.cpp:181] beginInternal(): host: xxx.xx.xxx.xxx port: 5555 url: /firmware.bin
[D][HTTPClient.cpp:850] connect():  connected to xxx.xx.xxx.xxx:5555
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'HTTP/1.1 200 OK'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Server: nginx/1.10.3'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Date: Tue, 13 Nov 2018 18:46:56 GMT'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Content-Type: application/octet-stream'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Content-Length: 851648'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Last-Modified: Tue, 13 Nov 2018 18:46:35 GMT'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Connection: close'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'ETag: "5beb1c0b-cfec0"'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Accept-Ranges: bytes'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: ''
[D][HTTPClient.cpp:968] handleHeaderResponse(): code: 200
[D][HTTPClient.cpp:971] handleHeaderResponse(): size: 851648
[D][Updater.cpp:129] begin(): OTA Partition: app1
[D][HTTPClient.cpp:240] end(): tcp stop
HTTP_UPDATE_FAILD Error (6): Update error: Stream Read Timeout[V][HTTPClient.cpp:140] beginInternal(): url: http://xxx.xx.xxx.xxx:5555/firmware.bin
[D][HTTPClient.cpp:181] beginInternal(): host: xxx.xx.xxx.xxx port: 5555 url: /firmware.bin
[D][HTTPClient.cpp:850] connect():  connected to xxx.xx.xxx.xxx:5555
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'HTTP/1.1 200 OK'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Server: nginx/1.10.3'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Date: Tue, 13 Nov 2018 18:47:00 GMT'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Content-Type: application/octet-stream'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Content-Length: 851648'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Last-Modified: Tue, 13 Nov 2018 18:46:35 GMT'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Connection: close'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'ETag: "5beb1c0b-cfec0"'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Accept-Ranges: bytes'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: ''
[D][HTTPClient.cpp:968] handleHeaderResponse(): code: 200
[D][HTTPClient.cpp:971] handleHeaderResponse(): size: 851648
[D][Updater.cpp:129] begin(): OTA Partition: app1
[D][HTTPClient.cpp:240] end(): tcp stop

can anybody help me please? 

I am using ESP32 with 16MByte flash memory with Arduino IDE set to "Minimal SPIFFS (Large apps with OTA"

**Comment by suculent** [comment]
Timeout either in server or client side. Try to extend timeout interval both in library and backend. 

How many seconds does it take to time out?

Odesláno z iPhonu

13. 11. 2018 v 19:54, Francisco Costa <notifications@github.com>:
